tap_install:
    sensitive_values:
        shared:
            ingress_domain: ENC[AES256_GCM,data:h/bMFNdQugZ7fPQ+XfyQdqBG8WPhcWKErWTaoKZ9uVM7iigvFlBPsAEAw3E=,iv:iTTjnWvMDSvxFUM4/zCZCq0V78x42ZLbsKeMt39x5b8=,tag:/dxRURIr/HUKhAEI9K8CZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140kfw9jqh7d63svrgf8rpjaf8mteg507va4s98pnjtl975qe6stqfpaxvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QnJqOC8wVXhjZm9HdjVE
            VlpTQnM1dXRvU2YrcjhTYXpIVWw3K3hoNVZnCjJCRkJSRk1SbkUrVHlHZFdMRzJC
            a25oQUt1TTYvTGdES1FzR2ZxaEcyN1EKLS0tIEZUTjJENy91bmtoQjVyTVFrbEVR
            UHdxdGk0NEFMWHRseHBreHRJaWIwNFUKltNDaad1rHw81dFvIvQ6bsC7FuzQXAWh
            7h4w2/LayyuyTEi5bYjDuyTEBgFrKMIl4l859QEOjj4DR6ntBqbbyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-14T21:35:18Z"
    mac: ENC[AES256_GCM,data:bv5nP34fZIp1ggZtz5eL0oJ0rzwWxT3LiirugkT6ng9UFDHv9PlkUUjRaX4r1ZPSEAVDu0DFRsZvIfyftm9lw6EmRTqatMcv7I+zLZ7FfVSqEZtVyA+D1ZDaN2fwdANfmZkoAtNcSyY52K8HApZTp7kYVdIEmixHmtiFxHMIypk=,iv:Yl7ydUjA15G3g9BRbaJA/PNoGqffRMpH7WGY0Xo0bXw=,tag:82zFQJOaA6ST5zg8FNv+8A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
